# Generated by Django 3.0 on 2020-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purbeurreuser',
            name='city',
            field=models.CharField(default='Paris', max_length=50),
            preserve_default=False,
        ),
    ]
